const villagerSpecies = [
    { type: 'Alligator' },
    { type: 'Anteater' },
    { type: 'Bird' },
    { type: 'Bear' },
    { type: 'Cat' },
    { type: 'Chicken' },
    { type: 'Cow' },
    { type: 'Cub' },
    { type: 'Deer' },
    { type: 'Dog' },
    { type: 'Duck' },
    { type: 'Eagle' },
    { type: 'Elephant' },
    { type: 'Frog' },
    { type: 'Goat' },
    { type: 'Hamster' },
    { type: 'Hippo' },
    { type: 'Horse' },
    { type: 'Koala' },
    { type: 'Kangaroo' },
    { type: 'Lion' },
    { type: 'Monkey' },
    { type: 'Mouse' },
    { type: 'Octopus' },
    { type: 'Penguin' },
    { type: 'Pig' },
    { type: 'Rabbit' },
    { type: 'Rhino' },
    { type: 'Sheep' },
    { type: 'Squirrel' },
    { type: 'Tiger' },
    { type: 'Wolf' }
]

export default villagerSpecies;